var car = "corolla";
var myName = "Ubaid";
var age = 17;
var isAdmin = true;
console.log("Is car == 'subaru'? I predict false");
console.log(car == "subaru");
console.log("Is car == 'corolla' ? I predict true");
console.log(car == "corolla");
console.log("Is myName == 'raza' ? I predict false");
console.log(myName == "raza");
console.log("Is myName == 'Ubaid' ? I predict true");
console.log(myName == "Ubaid");
console.log("Is age == 17 ? I predict true");
console.log(age == 17);
console.log("Is age == 19 ? I predict false");
console.log(age == 19);
console.log("Is age >= 12 ? I predict true");
console.log(age >= 12);
console.log("Is age <= 10 ? I predict false");
console.log(age <= 10);
console.log("Is isAdmin == true ? I predict true");
console.log(isAdmin == true);
console.log("Is isAdmin != true ? I predict false");
console.log(isAdmin != true);
